<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;

use Illuminate\Database\Seeder;

class BMenuSeeder extends Seeder
{
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');

        DB::table('b_menus')->insert([
            [
                'pk_menu' => 1,
                'fk_menu' => NULL,
                'fk_system' => 6,
                'fk_modulemenu' => NULL,
                'menulevel' => 1,
                'menu' => 'پذیرش ها',
                'menusec' => 'Receptions',
                'component' => NULL,
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => NULL,
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 4,
                'fk_menu' => NULL,
                'fk_system' => 1,
                'fk_modulemenu' => NULL,
                'menulevel' => 1,
                'menu' => 'واحد ها',
                'menusec' => 'Units',
                'component' => NULL,
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => NULL,
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 7,
                'fk_menu' => NULL,
                'fk_system' => 1,
                'fk_modulemenu' => NULL,
                'menulevel' => 1,
                'menu' => 'بانک ها',
                'menusec' => 'Banks',
                'component' => NULL,
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => NULL,
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],

            [
                'pk_menu' => 10,
                'fk_menu' => NULL,
                'fk_system' => 1,
                'fk_modulemenu' => NULL,
                'menulevel' => 1,
                'menu' => 'صندوق ها',
                'menusec' => 'Moneyboxes',
                'component' => NULL,
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => NULL,
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],

            [
                'pk_menu' => 13,
                'fk_menu' => NULL,
                'fk_system' => 1,
                'fk_modulemenu' => NULL,
                'menulevel' => 1,
                'menu' => 'حساب بانکی ها',
                'menusec' => 'Bankaccounts',
                'component' => NULL,
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => NULL,
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],

            [
                'pk_menu' => 16,
                'fk_menu' => NULL,
                'fk_system' => 1,
                'fk_modulemenu' => NULL,
                'menulevel' => 1,
                'menu' => 'انبار ها',
                'menusec' => 'Warehouses',
                'component' => NULL,
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => NULL,
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],

            [
                'pk_menu' => 19,
                'fk_menu' => NULL,
                'fk_system' => 1,
                'fk_modulemenu' => NULL,
                'menulevel' => 1,
                'menu' => 'محصولات',
                'menusec' => 'Products',
                'component' => NULL,
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => NULL,
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],

            [
                'pk_menu' => 22,
                'fk_menu' => NULL,
                'fk_system' => 6,
                'fk_modulemenu' => NULL,
                'menulevel' => 1,
                'menu' => 'مناطق و خدمات',
                'menusec' => 'Base Data',
                'component' => NULL,
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => NULL,
                'ordernumber' => 5,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],

            [
                'pk_menu' => 25,
                'fk_menu' => NULL,
                'fk_system' => 6,
                'fk_modulemenu' => NULL,
                'menulevel' => 1,
                'menu' => 'دلایل لغو',
                'menusec' => 'Reject Reason',
                'component' => NULL,
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => NULL,
                'ordernumber' => 6,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 26,
                'fk_menu' => NULL,
                'fk_system' => 6,
                'fk_modulemenu' => NULL,
                'menulevel' => 1,
                'menu' => 'شعب',
                'menusec' => 'Branchs',
                'component' => NULL,
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => NULL,
                'ordernumber' => 7,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],

            [
                'pk_menu' => 27,
                'fk_menu' => NULL,
                'fk_system' => 6,
                'fk_modulemenu' => NULL,
                'menulevel' => 1,
                'menu' => 'قطعات',
                'menusec' => 'Branchs',
                'component' => NULL,
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => NULL,
                'ordernumber' => 8,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 31,
                'fk_menu' => NULL,
                'fk_system' => 6,
                'fk_modulemenu' => NULL,
                'menulevel' => 1,
                'menu' => 'تکنسین ها',
                'menusec' => 'Technicians',
                'component' => NULL,
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => NULL,
                'ordernumber' => 4,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],

            [
                'pk_menu' => 37,
                'fk_menu' => NULL,
                'fk_system' => 6,
                'fk_modulemenu' => NULL,
                'menulevel' => 1,
                'menu' => 'شرکت ها',
                'menusec' => 'Companies',
                'component' => NULL,
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => NULL,
                'ordernumber' => 1,
                'isenable' => 0,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 40,
                'fk_menu' => NULL,
                'fk_system' => 6,
                'fk_modulemenu' => NULL,
                'menulevel' => 1,
                'menu' => 'فاکتور ها',
                'menusec' => 'Invoice',
                'component' => NULL,
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => NULL,
                'ordernumber' => 2,
                'isenable' => 0,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 43,
                'fk_menu' => NULL,
                'fk_system' => 7,
                'fk_modulemenu' => NULL,
                'menulevel' => 1,
                'menu' => 'تیکت ها',
                'menusec' => 'Ticket',
                'component' => NULL,
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => NULL,
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 46,
                'fk_menu' => NULL,
                'fk_system' => 6,
                'fk_modulemenu' => NULL,
                'menulevel' => 1,
                'menu' => 'کیف پول',
                'menusec' => 'Wallet',
                'component' => NULL,
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => NULL,
                'ordernumber' => 3,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 49,
                'fk_menu' => NULL,
                'fk_system' => 6,
                'fk_modulemenu' => NULL,
                'menulevel' => 1,
                'menu' => 'مرخصی',
                'menusec' => 'Leave Request',
                'component' => NULL,
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => NULL,
                'ordernumber' => 1,
                'isenable' => 0,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 56,
                'fk_menu' => NULL,
                'fk_system' => 1,
                'fk_modulemenu' => NULL,
                'menulevel' => 1,
                'menu' => 'اپلیکیشن ها',
                'menusec' => 'Technician Menus',
                'component' => NULL,
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => NULL,
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 58,
                'fk_menu' => NULL,
                'fk_system' => 1,
                'fk_modulemenu' => NULL,
                'menulevel' => 1,
                'menu' => 'کاربران',
                'menusec' => 'Users',
                'component' => NULL,
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => NULL,
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 61,
                'fk_menu' => NULL,
                'fk_system' => 1,
                'fk_modulemenu' => NULL,
                'menulevel' => 1,
                'menu' => 'نقش و دسترسی',
                'menusec' => 'Role & Access',
                'component' => NULL,
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => NULL,
                'ordernumber' => 8,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 66,
                'fk_menu' => NULL,
                'fk_system' => 7,
                'fk_modulemenu' => NULL,
                'menulevel' => 1,
                'menu' => ' پیامک',
                'menusec' => 'Sms',
                'component' => NULL,
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => NULL,
                'ordernumber' => 2,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 69,
                'fk_menu' => NULL,
                'fk_system' => 6,
                'fk_modulemenu' => NULL,
                'menulevel' => 1,
                'menu' => 'مشتریان',
                'menusec' => 'Customers',
                'component' => NULL,
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => NULL,
                'ordernumber' => 4,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 80,
                'fk_menu' => NULL,
                'fk_system' => 6,
                'fk_modulemenu' => NULL,
                'menulevel' => 1,
                'menu' => 'مالی',
                'menusec' => 'Accounting',
                'component' => NULL,
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => NULL,
                'ordernumber' => 10,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 84,
                'fk_menu' => NULL,
                'fk_system' => 1,
                'fk_modulemenu' => NULL,
                'menulevel' => 1,
                'menu' => 'دسته بندی محصولات',
                'menusec' => 'Product Category',
                'component' => NULL,
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => NULL,
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 87,
                'fk_menu' => NULL,
                'fk_system' => 5,
                'fk_modulemenu' => NULL,
                'menulevel' => 1,
                'menu' => 'دریافت',
                'menusec' => 'Receive',
                'component' => NULL,
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => NULL,
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 88,
                'fk_menu' => NULL,
                'fk_system' => 5,
                'fk_modulemenu' => NULL,
                'menulevel' => 1,
                'menu' => 'درخواست دریافت',
                'menusec' => 'Receive',
                'component' => NULL,
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => NULL,
                'ordernumber' => 2,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 89,
                'fk_menu' => NULL,
                'fk_system' => 5,
                'fk_modulemenu' => NULL,
                'menulevel' => 1,
                'menu' => 'پرداخت',
                'menusec' => 'Payment',
                'component' => NULL,
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => NULL,
                'ordernumber' => 3,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 90,
                'fk_menu' => NULL,
                'fk_system' => 5,
                'fk_modulemenu' => NULL,
                'menulevel' => 1,
                'menu' => 'درخواست پرداخت',
                'menusec' => 'PaymentRequest',
                'component' => NULL,
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => NULL,
                'ordernumber' => 4,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 91,
                'fk_menu' => NULL,
                'fk_system' => 3,
                'fk_modulemenu' => NULL,
                'menulevel' => 1,
                'menu' => 'انتقال',
                'menusec' => 'Transfer',
                'component' => NULL,
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => NULL,
                'ordernumber' => 5,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 92,
                'fk_menu' => NULL,
                'fk_system' => 5,
                'fk_modulemenu' => NULL,
                'menulevel' => 1,
                'menu' => 'چک های دریافتی',
                'menusec' => 'ReceivedChecks',
                'component' => NULL,
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => NULL,
                'ordernumber' => 6,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 93,
                'fk_menu' => NULL,
                'fk_system' => 5,
                'fk_modulemenu' => NULL,
                'menulevel' => 1,
                'menu' => 'چک ها پرداختی',
                'menusec' => 'PaidChecks',
                'component' => NULL,
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => NULL,
                'ordernumber' => 7,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 106,
                'fk_menu' => NULL,
                'fk_system' => 4,
                'fk_modulemenu' => NULL,
                'menulevel' => 1,
                'menu' => 'خرید',
                'menusec' => 'Purchase',
                'component' => NULL,
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => NULL,
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 109,
                'fk_menu' => NULL,
                'fk_system' => 4,
                'fk_modulemenu' => NULL,
                'menulevel' => 1,
                'menu' => 'فروش',
                'menusec' => 'Sale',
                'component' => NULL,
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => NULL,
                'ordernumber' => 2,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 112,
                'fk_menu' => NULL,
                'fk_system' => 4,
                'fk_modulemenu' => NULL,
                'menulevel' => 1,
                'menu' => 'برگشت از فروش',
                'menusec' => 'ReturnFromSale',
                'component' => NULL,
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => NULL,
                'ordernumber' => 3,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 115,
                'fk_menu' => NULL,
                'fk_system' => 3,
                'fk_modulemenu' => NULL,
                'menulevel' => 1,
                'menu' => 'رسید',
                'menusec' => 'Receipt',
                'component' => NULL,
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => NULL,
                'ordernumber' => 4,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 118,
                'fk_menu' => NULL,
                'fk_system' => 3,
                'fk_modulemenu' => NULL,
                'menulevel' => 1,
                'menu' => 'انتقال بین انبار',
                'menusec' => 'WarehouseTransfer',
                'component' => NULL,
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => NULL,
                'ordernumber' => 5,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 121,
                'fk_menu' => NULL,
                'fk_system' => 3,
                'fk_modulemenu' => NULL,
                'menulevel' => 1,
                'menu' => 'حواله',
                'menusec' => 'Havaleh',
                'component' => NULL,
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => NULL,
                'ordernumber' => 6,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 124,
                'fk_menu' => NULL,
                'fk_system' => 2,
                'fk_modulemenu' => NULL,
                'menulevel' => 1,
                'menu' => 'اسناد حسابداری',
                'menusec' => 'AccountingDocs',
                'component' => NULL,
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => NULL,
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 131,
                'fk_menu' => NULL,
                'fk_system' => 7,
                'fk_modulemenu' => NULL,
                'menulevel' => 1,
                'menu' => 'چت بات هوش مصنوعی',
                'menusec' => 'AI Chat Bot',
                'component' => NULL,
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => NULL,
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 135,
                'fk_menu' => NULL,
                'fk_system' => 1,
                'fk_modulemenu' => NULL,
                'menulevel' => 1,
                'menu' => 'سیستم',
                'menusec' => 'System',
                'component' => NULL,
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => NULL,
                'ordernumber' => 9,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 138,
                'fk_menu' => NULL,
                'fk_system' => 7,
                'fk_modulemenu' => NULL,
                'menulevel' => 1,
                'menu' => 'فعالیت ها',
                'menusec' => 'Events',
                'component' => NULL,
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => NULL,
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 142,
                'fk_menu' => NULL,
                'fk_system' => 7,
                'fk_modulemenu' => NULL,
                'menulevel' => 1,
                'menu' => 'نظرسنجی و امتیاز',
                'menusec' => 'Rating',
                'component' => NULL,
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => NULL,
                'ordernumber' => 8,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 144,
                'fk_menu' => NULL,
                'fk_system' => 6,
                'fk_modulemenu' => NULL,
                'menulevel' => 1,
                'menu' => 'هوش تجاری',
                'menusec' => 'Dashboards',
                'component' => NULL,
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => NULL,
                'ordernumber' => 15,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],






            //////////////////////////////////////////////////////////////////////////////////////////////

            //new

            [
                'pk_menu' => 2,
                'fk_menu' => 1,
                'fk_system' => 6,
                'fk_modulemenu' => NULL,
                'menulevel' => 2,
                'menu' => 'پذیرش جدید',
                'menusec' => 'New Reception',
                'component' => 'modules/homeease/reception/Reception',
                'secondcomponent' => NULL,
                'primarykey' => 'pk_reception',
                'icon' => 'uil:plus-circle',
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 5,
                'fk_menu' => 4,
                'fk_system' => 1,
                'fk_modulemenu' => NULL,
                'menulevel' => 2,
                'menu' => 'واحد جدید',
                'menusec' => 'New Units',
                'component' => 'modules/basic/Unit',
                'secondcomponent' => 'pk_unit',
                'primarykey' => NULL,
                'icon' => 'uil:plus-circle',
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],

            [
                'pk_menu' => 8,
                'fk_menu' => 7,
                'fk_system' => 1,
                'fk_modulemenu' => NULL,
                'menulevel' => 2,
                'menu' => 'بانک جدید',
                'menusec' => 'New Bank',
                'component' => 'modules/basic/Bank',
                'secondcomponent' => NULL,
                'primarykey' => 'pk_bank',
                'icon' => 'uil:plus-circle',
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],

            [
                'pk_menu' => 11,
                'fk_menu' => 10,
                'fk_system' => 1,
                'fk_modulemenu' => NULL,
                'menulevel' => 2,
                'menu' => 'صندوق جدید',
                'menusec' => 'New Moneyboxes',
                'component' => 'modules/basic/MoneyBox',
                'secondcomponent' => NULL,
                'primarykey' => 'pk_moneybox',
                'icon' => 'uil:plus-circle',
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],

            [
                'pk_menu' => 14,
                'fk_menu' => 13,
                'fk_system' => 1,
                'fk_modulemenu' => NULL,
                'menulevel' => 2,
                'menu' => 'حساب بانکی جدید',
                'menusec' => 'New Bankaccount',
                'component' => 'modules/basic/BankAccount',
                'secondcomponent' => NULL,
                'primarykey' => 'pk_bankaccount',
                'icon' => 'uil:plus-circle',
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],

            [
                'pk_menu' => 17,
                'fk_menu' => 16,
                'fk_system' => 1,
                'fk_modulemenu' => NULL,
                'menulevel' => 2,
                'menu' => 'انبار جدید',
                'menusec' => 'New Warehouses',
                'component' => 'modules/basic/Warehouse',
                'secondcomponent' => NULL,
                'primarykey' => 'pk_warehouse',
                'icon' => 'uil:plus-circle',
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],

            [
                'pk_menu' => 20,
                'fk_menu' => 19,
                'fk_system' => 1,
                'fk_modulemenu' => NULL,
                'menulevel' => 2,
                'menu' => 'محصول جدید',
                'menusec' => 'New Product',
                'component' => 'modules/basic/Product',
                'secondcomponent' => NULL,
                'primarykey' => 'pk_product',
                'icon' => 'uil:plus-circle',
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],

            [
                'pk_menu' => 23,
                'fk_menu' => 22,
                'fk_system' => 6,
                'fk_modulemenu' => NULL,
                'menulevel' => 2,
                'menu' => 'اطلاعات جغرافیایی',
                'menusec' => 'Geo Data',
                'component' => 'modules/homeease/GeoData',
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => 'uil:list-ui-alt',
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 24,
                'fk_menu' => 22,
                'fk_system' => 6,
                'fk_modulemenu' => NULL,
                'menulevel' => 2,
                'menu' => 'دسته بندی خدمات',
                'menusec' => 'Service List',
                'component' => 'modules/homeease/ElementData',
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => 'uil:list-ui-alt',
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],

            [
                'pk_menu' => 32,
                'fk_menu' => 31,
                'fk_system' => 6,
                'fk_modulemenu' => NULL,
                'menulevel' => 2,
                'menu' => 'تکنسین جدید',
                'menusec' => 'New Technician',
                'component' => 'modules/homeease/Technician',
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => 'uil:plus-circle',
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 86,
                'fk_menu' => 84,
                'fk_system' => 1,
                'fk_modulemenu' => NULL,
                'menulevel' => 2,
                'menu' => 'دسته بندی محصول جدید',
                'menusec' => 'New Product Category',
                'component' => 'modules/basic/ProductCategory',
                'secondcomponent' => NULL,
                'primarykey' => 'pk_product',
                'icon' => 'uil:plus-circle',
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 29,
                'fk_menu' => 26,
                'fk_system' => 6,
                'fk_modulemenu' => NULL,
                'menulevel' => 2,
                'menu' => 'شعبه جدید',
                'menusec' => 'New Branch',
                'component' => 'modules/homeease/Agency',
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => 'uil:plus-circle',
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 34,
                'fk_menu' => 31,
                'fk_system' => 6,
                'fk_modulemenu' => NULL,
                'menulevel' => 2,
                'menu' => 'فرم های استخدام',
                'menusec' => 'Technician Request',
                'component' => 'modules/List',
                'secondcomponent' => NULL,
                'primarykey' => 'pk_technician',
                'icon' => 'uil:file-edit-alt',
                'ordernumber' => 5,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 38,
                'fk_menu' => 37,
                'fk_system' => 6,
                'fk_modulemenu' => NULL,
                'menulevel' => 2,
                'menu' => 'شرکت جدید',
                'menusec' => 'New Company',
                'component' => '',
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => 'uil:plus-circle',
                'ordernumber' => 1,
                'isenable' => 0,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 41,
                'fk_menu' => NULL,
                'fk_system' => 6,
                'fk_modulemenu' => NULL,
                'menulevel' => 2,
                'menu' => 'مالی پذیرش',
                'menusec' => 'New Invoice',
                'component' => 'modules/homeease/ReceptionAccounting',
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => 'uil:plus-circle',
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 44,
                'fk_menu' => null,
                'fk_system' => 7,
                'fk_modulemenu' => NULL,
                'menulevel' => 2,
                'menu' => 'تیکت جدید',
                'menusec' => 'New Ticket',
                'component' => 'modules/crm/Ticket',
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => 'uil:plus-circle',
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 47,
                'fk_menu' => 46,
                'fk_system' => 6,
                'fk_modulemenu' => NULL,
                'menulevel' => 2,
                'menu' => 'شارژ کیف پول',
                'menusec' => 'Wallet Increase',
                'component' => 'modules/homeease/WalletIncrease',
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => 'uil:plus-circle',
                'ordernumber' => 3,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 48,
                'fk_menu' => 46,
                'fk_system' => 6,
                'fk_modulemenu' => null,
                'menulevel' => 2,
                'menu' => 'لیست تراکنش ها',
                'menusec' => 'Transaction List',
                'component' => 'modules/List',
                'secondcomponent' => NULL,
                'primarykey' => 'pk_wallettransaction',
                'icon' => 'uil:list-ul',
                'ordernumber' => 2,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 50,
                'fk_menu' => 49,
                'fk_system' => 6,
                'fk_modulemenu' => NULL,
                'menulevel' => 2,
                'menu' => 'مرخصی جدید',
                'menusec' => 'New Leave Request',
                'component' => '',
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => 'uil:plus-circle',
                'ordernumber' => 1,
                'isenable' => 0,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 53,
                'fk_menu' => 25,
                'fk_system' => 6,
                'fk_modulemenu' => NULL,
                'menulevel' => 2,
                'menu' => 'دلیل لغو جدید',
                'menusec' => 'New Reject Reason',
                'component' => 'modules/homeease/RejectReason',
                'secondcomponent' => NULL,
                'primarykey' => 'pk_rejectreason',
                'icon' => 'uil:plus-circle',
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 55,
                'fk_menu' => 27,
                'fk_system' => 6,
                'fk_modulemenu' => NULL,
                'menulevel' => 2,
                'menu' => 'قطعه جدید',
                'menusec' => 'New Product',
                'component' => 'modules/homeease/Product',
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => 'uil:plus-circle',
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 57,
                'fk_menu' => 56,
                'fk_system' => 6,
                'fk_modulemenu' => NULL,
                'menulevel' => 2,
                'menu' => 'تمامی منو های اپ تکنسین',
                'menusec' => 'Technician All Menus',
                'component' => NULL,
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => 'uil:list-ul',
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 59,
                'fk_menu' => 58,
                'fk_system' => 1,
                'fk_modulemenu' => NULL,
                'menulevel' => 2,
                'menu' => 'کاربر جدید',
                'menusec' => 'New User',
                'component' => 'modules/basic/User',
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => 'uil:plus-circle',
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],

            [
                'pk_menu' => 62,
                'fk_menu' => 61,
                'fk_system' => 1,
                'fk_modulemenu' => NULL,
                'menulevel' => 2,
                'menu' => 'نقش جدید',
                'menusec' => 'New Role',
                'component' => 'modules/basic/Role',
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => 'uil:plus-circle',
                'ordernumber' => 2,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 64,
                'fk_menu' => 61,
                'fk_system' => 1,
                'fk_modulemenu' => NULL,
                'menulevel' => 2,
                'menu' => 'نقش های کاربر',
                'menusec' => 'User Roles',
                'component' => 'modules/basic/UserRoles',
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => 'uil:plus-circle',
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 65,
                'fk_menu' => 61,
                'fk_system' => 1,
                'fk_modulemenu' => NULL,
                'menulevel' => 2,
                'menu' => 'ماژول های نقش',
                'menusec' => 'Role Modules',
                'component' => 'modules/basic/RoleModules',
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => 'uil:plus-circle',
                'ordernumber' => 4,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],

            [
                'pk_menu' => 67,
                'fk_menu' => 66,
                'fk_system' => 7,
                'fk_modulemenu' => NULL,
                'menulevel' => 2,
                'menu' => 'ارسال پیامک',
                'menusec' => 'Send Sms',
                'component' => 'modules/crm/SendSms',
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => 'uil:plus-circle',
                'ordernumber' => 1,
                'isenable' => 0,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 68,
                'fk_menu' => 66,
                'fk_system' => 7,
                'fk_modulemenu' => NULL,
                'menulevel' => 2,
                'menu' => 'صندوق خروجی',
                'menusec' => 'Outbox',
                'component' => 'modules/List',
                'secondcomponent' => NULL,
                'primarykey' => 'pk_sms',
                'icon' => 'uil:list-ul',
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 70,
                'fk_menu' => 69,
                'fk_system' => 6,
                'fk_modulemenu' => NULL,
                'menulevel' => 2,
                'menu' => 'مشتری جدید',
                'menusec' => 'New Customer',
                'component' => 'modules/homeease/Customer',
                'secondcomponent' => NULL,
                'primarykey' => 'id',
                'icon' => 'uil:plus-circle',
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 72,
                'fk_menu' => 1,
                'fk_system' => 6,
                'fk_modulemenu' => 41,
                'menulevel' => 2,
                'menu' => 'گزارش جامع',
                'menusec' => 'All Report',
                'component' => 'modules/homeease/reception/Report',
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => 'uil:comment-chart-line',
                'ordernumber' => 10,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 73,
                'fk_menu' => 56,
                'fk_system' => 6,
                'fk_modulemenu' => NULL,
                'menulevel' => 2,
                'menu' => 'تمامی منو های اپ مشتری',
                'menusec' => 'Customer All Menus',
                'component' => NULL,
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => 'uil:list-ul',
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],

            [
                'pk_menu' => 74,
                'fk_menu' => 46,
                'fk_system' => 6,
                'fk_modulemenu' => null,
                'menulevel' => 2,
                'menu' => 'کیف پول کاربران',
                'menusec' => 'User Wallets',
                'component' => 'modules/List',
                'secondcomponent' => NULL,
                'primarykey' => 'pk_wallettransaction',
                'icon' => 'uil:list-ul',
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 75,
                'fk_menu' => 46,
                'fk_system' => 6,
                'fk_modulemenu' => NULL,
                'menulevel' => 2,
                'menu' => 'کسر از کیف پول',
                'menusec' => 'WalletDecrease',
                'component' => 'modules/homeease/WalletDecrease',
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => 'uil:plus-circle',
                'ordernumber' => 4,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 76,
                'fk_menu' => NULL,
                'fk_system' => 6,
                'fk_modulemenu' => null,
                'menulevel' => 2,
                'menu' => 'تسویه با تکنسین',
                'menusec' => 'Settle',
                'component' => 'modules/homeease/TechnicianSettle',
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => 'uil:money-stack',
                'ordernumber' => 3,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 78,
                'fk_menu' => 61,
                'fk_system' => 1,
                'fk_modulemenu' => NULL,
                'menulevel' => 2,
                'menu' => 'کاربران نقش ها',
                'menusec' => 'Role Users',
                'component' => 'modules/basic/RoleUsers',
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => 'uil:plus-circle',
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 79,
                'fk_menu' => 22,
                'fk_system' => 6,
                'fk_modulemenu' => NULL,
                'menulevel' => 2,
                'menu' => 'ایرادات دستگاه ها',
                'menusec' => 'Device Issues',
                'component' => 'modules/homeease/DeviceIssues',
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => 'uil:list-ui-alt',
                'ordernumber' => 3,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 81,
                'fk_menu' => 80,
                'fk_system' => 6,
                'fk_modulemenu' => NUll,
                'menulevel' => 2,
                'menu' => 'گزارش ماهانه',
                'menusec' => 'Monthly Report',
                'component' => 'modules/homeease/report/MonthlyAccounting',
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => 'uil:money-stack',
                'ordernumber' => 2,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 94,
                'fk_menu' => 88,
                'fk_system' => 5,
                'fk_modulemenu' => NULL,
                'menulevel' => 2,
                'menu' => 'درخواست دریافت جدید',
                'menusec' => 'NewReceiveRequest',
                'component' => 'modules/finance/receive/ReceiveRequest',
                'secondcomponent' => NULL,
                'primarykey' => 'pk_receive_request',
                'icon' => 'uil:plus-circle',
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 95,
                'fk_menu' => 89,
                'fk_system' => 5,
                'fk_modulemenu' => NULL,
                'menulevel' => 2,
                'menu' => 'پرداخت جدید',
                'menusec' => 'NewPayment',
                'component' => 'modules/finance/payment/Payment',
                'secondcomponent' => NULL,
                'primarykey' => 'pk_payment',
                'icon' => 'uil:plus-circle',
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 96,
                'fk_menu' => 90,
                'fk_system' => 5,
                'fk_modulemenu' => NULL,
                'menulevel' => 2,
                'menu' => 'درخواست پرداخت جدید',
                'menusec' => 'NewPaymentRequest',
                'component' => 'modules/finance/payment/PaymentRequest',
                'secondcomponent' => NULL,
                'primarykey' => 'pk_payment_request',
                'icon' => 'uil:plus-circle',
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 97,
                'fk_menu' => 91,
                'fk_system' => 3,
                'fk_modulemenu' => NULL,
                'menulevel' => 2,
                'menu' => 'انتقال جدید',
                'menusec' => 'NewTransfer',
                'component' => 'modules/finance/transfer/Transfer',
                'secondcomponent' => NULL,
                'primarykey' => 'pk_transfer',
                'icon' => 'uil:plus-circle',
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 98,
                'fk_menu' => 92,
                'fk_system' => 5,
                'fk_modulemenu' => NULL,
                'menulevel' => 2,
                'menu' => 'چک دریافتی جدید',
                'menusec' => 'NewReceivedCheck',
                'component' => 'modules/finance/checks/Received',
                'secondcomponent' => NULL,
                'primarykey' => 'pk_received_check',
                'icon' => 'uil:plus-circle',
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 99,
                'fk_menu' => 93,
                'fk_system' => 5,
                'fk_modulemenu' => NULL,
                'menulevel' => 2,
                'menu' => 'چک پرداختی جدید',
                'menusec' => 'NewPaidCheck',
                'component' => 'modules/finance/checks/Paid',
                'secondcomponent' => NULL,
                'primarykey' => 'pk_paid_check',
                'icon' => 'uil:plus-circle',
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 108,
                'fk_menu' => 106,
                'fk_system' => 4,
                'fk_modulemenu' => NULL,
                'menulevel' => 2,
                'menu' => 'خرید جدید',
                'menusec' => 'NewPurchase',
                'component' => 'modules/commerce/BuyInvoice',
                'secondcomponent' => NULL,
                'primarykey' => 'pk_invoice',
                'icon' => 'uil:plus-circle',
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 111,
                'fk_menu' => 109,
                'fk_system' => 4,
                'fk_modulemenu' => NULL,
                'menulevel' => 2,
                'menu' => 'فروش جدید',
                'menusec' => 'NewSale',
                'component' => 'modules/commerce/SaleInvoice',
                'secondcomponent' => NULL,
                'primarykey' => 'pk_invoice',
                'icon' => 'uil:plus-circle',
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 114,
                'fk_menu' => 112,
                'fk_system' => 4,
                'fk_modulemenu' => NULL,
                'menulevel' => 2,
                'menu' => 'برگشت از فروش جدید',
                'menusec' => 'NewReturn',
                'component' => 'modules/commerce/ReturnInvoice',
                'secondcomponent' => NULL,
                'primarykey' => 'pk_invoice',
                'icon' => 'uil:plus-circle',
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 117,
                'fk_menu' => 115,
                'fk_system' => 3,
                'fk_modulemenu' => NULL,
                'menulevel' => 2,
                'menu' => 'رسید انبار جدید',
                'menusec' => 'New Warehouse Receipt',
                'component' => 'modules/warehouse/WarehouseReceiveDoc',
                'secondcomponent' => NULL,
                'primarykey' => 'pk_receipt',
                'icon' => 'uil:plus-circle',
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 120,
                'fk_menu' => 118,
                'fk_system' => 3,
                'fk_modulemenu' => NULL,
                'menulevel' => 2,
                'menu' => 'انتقال جدید',
                'menusec' => 'NewTransfer',
                'component' => 'modules/warehouse/transfer/New',
                'secondcomponent' => NULL,
                'primarykey' => 'pk_transfer',
                'icon' => 'uil:plus-circle',
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 123,
                'fk_menu' => 121,
                'fk_system' => 3,
                'fk_modulemenu' => NULL,
                'menulevel' => 2,
                'menu' => 'حواله جدید',
                'menusec' => 'New Exit From Warehouse',
                'component' => 'modules/warehouse/WarehouseExitDoc',
                'secondcomponent' => NULL,
                'primarykey' => 'pk_havaleh',
                'icon' => 'uil:plus-circle',
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 126,
                'fk_menu' => 124,
                'fk_system' => 2,
                'fk_modulemenu' => NULL,
                'menulevel' => 2,
                'menu' => 'سند حسابداری جدید',
                'menusec' => 'NewAccountingDoc',
                'component' => 'modules/accounting/docs/New',
                'secondcomponent' => NULL,
                'primarykey' => 'pk_accountingdoc',
                'icon' => 'uil:plus-circle',
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 128,
                'fk_menu' => 66,
                'fk_system' => 7,
                'fk_modulemenu' => NULL,
                'menulevel' => 2,
                'menu' => 'الگوی پیامک',
                'menusec' => 'Sms Pattern',
                'component' => 'modules/crm/SmsPattern',
                'secondcomponent' => NULL,
                'primarykey' => 'pk_smspattern',
                'icon' => 'uil:plus-circle',
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 132,
                'fk_menu' => null,
                'fk_system' => 7,
                'fk_modulemenu' => NULL,
                'menulevel' => 2,
                'menu' => 'جزییات چت هوش مصنوعی',
                'menusec' => 'AI Bot Chats',
                'component' => 'modules/crm/AIChat',
                'secondcomponent' => NULL,
                'primarykey' => 'pk_aiconversationmessage',
                'icon' => 'uil:plus-circle',
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 134,
                'fk_menu' => 131,
                'fk_system' => 7,
                'fk_modulemenu' => NULL,
                'menulevel' => 2,
                'menu' => 'تنظیمات چت بات',
                'menusec' => 'AI Chat Bot Setting',
                'component' => 'modules/crm/AIChatSetting',
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => 'uil:setting',
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 136,
                'fk_menu' => 135,
                'fk_system' => 1,
                'fk_modulemenu' => NULL,
                'menulevel' => 2,
                'menu' => 'ورود اطلاعات سیستم تعمیرات',
                'menusec' => 'Import Data',
                'component' => 'modules/basic/ImportFromExcel',
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => 'uil:plus-circle',
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 137,
                'fk_menu' => 135,
                'fk_system' => 1,
                'fk_modulemenu' => NULL,
                'menulevel' => 2,
                'menu' => 'تنظیمات',
                'menusec' => 'Setting',
                'component' => 'modules/basic/Setting',
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => 'uil:plus-circle',
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 52,
                'fk_menu' => 142,
                'fk_system' => 6,
                'fk_modulemenu' => NULL,
                'menulevel' => 2,
                'menu' => 'نظرات مشتریان',
                'menusec' => 'Technician Rating List',
                'component' => 'modules/List',
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => 'uil:star',
                'ordernumber' => 5,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 145,
                'fk_menu' => 144,
                'fk_system' => 6,
                'fk_modulemenu' => NUll,
                'menulevel' => 2,
                'menu' => 'داشبورد پذیرش ها',
                'menusec' => 'Receptions',
                'component' => 'modules/homeease/dashboards/Reception',
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => 'uil:money-stack',
                'ordernumber' => 2,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],




            //////////////////////////////////////////////////////////////////////////////////////////////

            //list

            [
                'pk_menu' => 3,
                'fk_menu' => 1,
                'fk_system' => 6,
                'fk_modulemenu' => 2,
                'menulevel' => 2,
                'menu' => 'لیست پذیرش ها',
                'menusec' => 'Reception List',
                'component' => 'modules/List',
                'secondcomponent' => NULL,
                'primarykey' => 'pk_reception',
                'icon' => 'uil:list-ul',
                'ordernumber' => 2,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 127,
                'fk_menu' => 1,
                'fk_system' => 6,
                'fk_modulemenu' => 2,
                'menulevel' => 2,
                'menu' => 'پذیرش های اپراتور',
                'menusec' => 'Operator Reception List',
                'component' => 'modules/List',
                'secondcomponent' => NULL,
                'primarykey' => 'pk_reception',
                'icon' => 'uil:list-ul',
                'ordernumber' => 3,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 6,
                'fk_menu' => 4,
                'fk_system' => 1,
                'fk_modulemenu' => 5,
                'menulevel' => 2,
                'menu' => 'لیست واحدهای اندازه گیری',
                'menusec' => 'Units List',
                'component' => 'modules/List',
                'secondcomponent' => NULL,
                'primarykey' => 'pk_unit',
                'icon' => 'uil:list-ul',
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 9,
                'fk_menu' => 7,
                'fk_system' => 1,
                'fk_modulemenu' => 8,
                'menulevel' => 2,
                'menu' => 'لیست بانک ها',
                'menusec' => 'Banks List',
                'component' => 'modules/List',
                'secondcomponent' => NULL,
                'primarykey' => 'pk_bank',
                'icon' => 'uil:list-ul',
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 12,
                'fk_menu' => 10,
                'fk_system' => 1,
                'fk_modulemenu' => 11,
                'menulevel' => 2,
                'menu' => 'لیست صندوق ها',
                'menusec' => 'Moneyboxes List',
                'component' => 'modules/List',
                'secondcomponent' => NULL,
                'primarykey' => 'pk_moneybox',
                'icon' => 'uil:list-ul',
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 15,
                'fk_menu' => 13,
                'fk_system' => 1,
                'fk_modulemenu' => 14,
                'menulevel' => 2,
                'menu' => 'لیست حساب بانکی',
                'menusec' => 'Bankaccounts List',
                'component' => 'modules/List',
                'secondcomponent' => NULL,
                'primarykey' => 'pk_bankaccount',
                'icon' => 'uil:list-ul',
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 18,
                'fk_menu' => 16,
                'fk_system' => 1,
                'fk_modulemenu' => 17,
                'menulevel' => 2,
                'menu' => 'لیست انبار ها',
                'menusec' => 'Warehouses List',
                'component' => 'modules/List',
                'secondcomponent' => NULL,
                'primarykey' => 'pk_warehouse',
                'icon' => 'uil:list-ul',
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 21,
                'fk_menu' => 19,
                'fk_system' => 1,
                'fk_modulemenu' => 20,
                'menulevel' => 2,
                'menu' => 'لیست محصولات',
                'menusec' => 'Products List',
                'component' => 'modules/List',
                'secondcomponent' => NULL,
                'primarykey' => 'pk_product',
                'icon' => 'uil:list-ul',
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 28,
                'fk_menu' => 27,
                'fk_system' => 6,
                'fk_modulemenu' => 55,
                'menulevel' => 2,
                'menu' => 'لیست قطعات',
                'menusec' => 'Products',
                'component' => 'modules/List',
                'secondcomponent' => NULL,
                'primarykey' => 'pk_product',
                'icon' => 'uil:list-ul',
                'ordernumber' => 2,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 30,
                'fk_menu' => 26,
                'fk_system' => 6,
                'fk_modulemenu' => 29,
                'menulevel' => 2,
                'menu' => 'لیست شعب',
                'menusec' => 'Branches',
                'component' => 'modules/List',
                'secondcomponent' => NULL,
                'primarykey' => 'pk_branch',
                'icon' => 'uil:list-ul',
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 33,
                'fk_menu' => 31,
                'fk_system' => 6,
                'fk_modulemenu' => 32,
                'menulevel' => 2,
                'menu' => 'لیست تکنسین ها',
                'menusec' => 'Technician List',
                'component' => 'modules/List',
                'secondcomponent' => NULL,
                'primarykey' => 'pk_technician',
                'icon' => 'uil:list-ul',
                'ordernumber' => 2,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 39,
                'fk_menu' => 37,
                'fk_system' => 6,
                'fk_modulemenu' => 38,
                'menulevel' => 2,
                'menu' => 'لیست شرکت ها',
                'menusec' => 'Company List',
                'component' => 'modules/List',
                'secondcomponent' => NULL,
                'primarykey' => 'pk_company',
                'icon' => 'uil:list-ul',
                'ordernumber' => 1,
                'isenable' => 0,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 42,
                'fk_menu' => 1,
                'fk_system' => 6,
                'fk_modulemenu' => 41,
                'menulevel' => 2,
                'menu' => 'فاکتور',
                'menusec' => 'Invoice List',
                'component' => 'modules/List',
                'secondcomponent' => NULL,
                'primarykey' => 'pk_invoice',
                'icon' => 'uil:dollar-sign-alt',
                'ordernumber' => 3,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 45,
                'fk_menu' => 43,
                'fk_system' => 7,
                'fk_modulemenu' => 44,
                'menulevel' => 2,
                'menu' => 'لیست تیکت ها',
                'menusec' => 'Ticket List',
                'component' => 'modules/List',
                'secondcomponent' => NULL,
                'primarykey' => 'pk_ticket',
                'icon' => 'uil:list-ul',
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 51,
                'fk_menu' => 31,
                'fk_system' => 6,
                'fk_modulemenu' => 50,
                'menulevel' => 2,
                'menu' => 'لیست مرخصی ها',
                'menusec' => 'Leave Request List',
                'component' => 'modules/List',
                'secondcomponent' => NULL,
                'primarykey' => 'pk_leaverequest',
                'icon' => 'uil:house-user',
                'ordernumber' => 4,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 54,
                'fk_menu' => 25,
                'fk_system' => 6,
                'fk_modulemenu' => 53,
                'menulevel' => 2,
                'menu' => 'لیست دلایل لغو',
                'menusec' => 'Reject Reason List',
                'component' => 'modules/List',
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => 'uil:list-ul',
                'ordernumber' => 2,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],

            [
                'pk_menu' => 60,
                'fk_menu' => 58,
                'fk_system' => 7,
                'fk_modulemenu' => 59,
                'menulevel' => 2,
                'menu' => 'لیست کاربران',
                'menusec' => 'Users List',
                'component' => 'modules/List',
                'secondcomponent' => NULL,
                'primarykey' => 'id',
                'icon' => 'uil:list-ul',
                'ordernumber' => 2,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 63,
                'fk_menu' => 61,
                'fk_system' => 7,
                'fk_modulemenu' => 62,
                'menulevel' => 2,
                'menu' => 'لیست نقش ها',
                'menusec' => 'Role List',
                'component' => 'modules/List',
                'secondcomponent' => NULL,
                'primarykey' => 'id',
                'icon' => 'uil:list-ul',
                'ordernumber' => 2,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 71,
                'fk_menu' => 69,
                'fk_system' => 6,
                'fk_modulemenu' => 70,
                'menulevel' => 2,
                'menu' => 'لیست مشتری ها',
                'menusec' => 'Customer List',
                'component' => 'modules/List',
                'secondcomponent' => NULL,
                'primarykey' => 'id',
                'icon' => 'uil:list-ul',
                'ordernumber' => 5,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 77,
                'fk_menu' => 80,
                'fk_system' => 6,
                'fk_modulemenu' => 76,
                'menulevel' => 2,
                'menu' => 'تسویه حساب',
                'menusec' => 'Settle List',
                'component' => 'modules/List',
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => 'uil:money-stack',
                'ordernumber' => 3,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 82,
                'fk_menu' => 1,
                'fk_system' => 6,
                'fk_modulemenu' => 2,
                'menulevel' => 2,
                'menu' => 'سرنخ ها',
                'menusec' => 'Reception List',
                'component' => 'modules/List',
                'secondcomponent' => NULL,
                'primarykey' => 'pk_reception',
                'icon' => 'uil:list-ul',
                'ordernumber' => 8,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 83,
                'fk_menu' => 1,
                'fk_system' => 6,
                'fk_modulemenu' => 2,
                'menulevel' => 2,
                'menu' => 'بایگانی',
                'menusec' => 'Reception List',
                'component' => 'modules/List',
                'secondcomponent' => NULL,
                'primarykey' => 'pk_reception',
                'icon' => 'uil:list-ul',
                'ordernumber' => 9,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 85,
                'fk_menu' => 84,
                'fk_system' => 1,
                'fk_modulemenu' => 86,
                'menulevel' => 2,
                'menu' => 'لیست دسته بندی محصولات',
                'menusec' => 'Products List',
                'component' => 'modules/List',
                'secondcomponent' => NULL,
                'primarykey' => 'pk_product',
                'icon' => 'uil:list-ul',
                'ordernumber' => 3,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 100,
                'fk_menu' => 88,
                'fk_system' => 5,
                'fk_modulemenu' => 94,
                'menulevel' => 2,
                'menu' => 'لیست درخواست‌های دریافت',
                'menusec' => 'ReceiveRequest List',
                'component' => 'modules/List',
                'secondcomponent' => NULL,
                'primarykey' => 'pk_receive_request',
                'icon' => 'uil:list-ul',
                'ordernumber' => 2,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 101,
                'fk_menu' => 89,
                'fk_system' => 5,
                'fk_modulemenu' => 95,
                'menulevel' => 2,
                'menu' => 'لیست پرداخت‌ها',
                'menusec' => 'Payment List',
                'component' => 'modules/List',
                'secondcomponent' => NULL,
                'primarykey' => 'pk_payment',
                'icon' => 'uil:list-ul',
                'ordernumber' => 2,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 102,
                'fk_menu' => 90,
                'fk_system' => 5,
                'fk_modulemenu' => 96,
                'menulevel' => 2,
                'menu' => 'لیست درخواست‌های پرداخت',
                'menusec' => 'PaymentRequest List',
                'component' => 'modules/List',
                'secondcomponent' => NULL,
                'primarykey' => 'pk_payment_request',
                'icon' => 'uil:list-ul',
                'ordernumber' => 2,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 103,
                'fk_menu' => 91,
                'fk_system' => 5,
                'fk_modulemenu' => 97,
                'menulevel' => 2,
                'menu' => 'لیست انتقال‌ها',
                'menusec' => 'Transfer List',
                'component' => 'modules/List',
                'secondcomponent' => NULL,
                'primarykey' => 'pk_transfer',
                'icon' => 'uil:list-ul',
                'ordernumber' => 2,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 104,
                'fk_menu' => 92,
                'fk_system' => 5,
                'fk_modulemenu' => 98,
                'menulevel' => 2,
                'menu' => 'لیست چک‌های دریافتی',
                'menusec' => 'ReceivedCheck List',
                'component' => 'modules/List',
                'secondcomponent' => NULL,
                'primarykey' => 'pk_received_check',
                'icon' => 'uil:list-ul',
                'ordernumber' => 2,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 105,
                'fk_menu' => 93,
                'fk_system' => 5,
                'fk_modulemenu' => 99,
                'menulevel' => 2,
                'menu' => 'لیست چک‌های پرداختی',
                'menusec' => 'PaidCheck List',
                'component' => 'modules/List',
                'secondcomponent' => NULL,
                'primarykey' => 'pk_paid_check',
                'icon' => 'uil:list-ul',
                'ordernumber' => 2,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 107,
                'fk_menu' => 106,
                'fk_system' => 4,
                'fk_modulemenu' => 108,
                'menulevel' => 2,
                'menu' => 'لیست خریدها',
                'menusec' => 'Purchase List',
                'component' => 'modules/List',
                'secondcomponent' => NULL,
                'primarykey' => 'pk_purchase',
                'icon' => 'uil:list-ul',
                'ordernumber' => 2,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 110,
                'fk_menu' => 109,
                'fk_system' => 4,
                'fk_modulemenu' => 111,
                'menulevel' => 2,
                'menu' => 'لیست فروش‌ها',
                'menusec' => 'Sale List',
                'component' => 'modules/List',
                'secondcomponent' => NULL,
                'primarykey' => 'pk_invoice',
                'icon' => 'uil:list-ul',
                'ordernumber' => 2,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 113,
                'fk_menu' => 112,
                'fk_system' => 4,
                'fk_modulemenu' => 114,
                'menulevel' => 2,
                'menu' => 'لیست برگشت‌ها',
                'menusec' => 'Return List',
                'component' => 'modules/List',
                'secondcomponent' => NULL,
                'primarykey' => 'pk_invoice',
                'icon' => 'uil:list-ul',
                'ordernumber' => 2,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 116,
                'fk_menu' => 115,
                'fk_system' => 3,
                'fk_modulemenu' => 117,
                'menulevel' => 2,
                'menu' => 'لیست رسیدهای انبار',
                'menusec' => 'Receipt List',
                'component' => 'modules/List',
                'secondcomponent' => NULL,
                'primarykey' => 'pk_receipt',
                'icon' => 'uil:list-ul',
                'ordernumber' => 2,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 119,
                'fk_menu' => 118,
                'fk_system' => 4,
                'fk_modulemenu' => 120,
                'menulevel' => 2,
                'menu' => 'لیست انتقال بین انبار',
                'menusec' => 'Transfer List',
                'component' => 'modules/List',
                'secondcomponent' => NULL,
                'primarykey' => 'pk_transfer',
                'icon' => 'uil:list-ul',
                'ordernumber' => 2,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 122,
                'fk_menu' => 121,
                'fk_system' => 3,
                'fk_modulemenu' => 123,
                'menulevel' => 2,
                'menu' => 'لیست حواله انبار',
                'menusec' => 'Havaleh List',
                'component' => 'modules/List',
                'secondcomponent' => NULL,
                'primarykey' => 'pk_havaleh',
                'icon' => 'uil:list-ul',
                'ordernumber' => 2,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 125,
                'fk_menu' => 124,
                'fk_system' => 2,
                'fk_modulemenu' => 126,
                'menulevel' => 2,
                'menu' => 'لیست اسناد حسابداری',
                'menusec' => 'Accounting Doc List',
                'component' => 'modules/List',
                'secondcomponent' => NULL,
                'primarykey' => 'pk_accountingdoc',
                'icon' => 'uil:list-ul',
                'ordernumber' => 2,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 129,
                'fk_menu' => 66,
                'fk_system' => 7,
                'fk_modulemenu' => 128,
                'menulevel' => 2,
                'menu' => 'الگوهای پیامک',
                'menusec' => 'Automation Sms',
                'component' => 'modules/List',
                'secondcomponent' => NULL,
                'primarykey' => 'pk_smspattern',
                'icon' => 'uil:list-ul',
                'ordernumber' => 2,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 130,
                'fk_menu' => 135,
                'fk_system' => 1,
                'fk_modulemenu' => null,
                'menulevel' => 2,
                'menu' => 'گزارش ورود ها',
                'menusec' => 'Login Report',
                'component' => 'modules/List',
                'secondcomponent' => NULL,
                'primarykey' => '',
                'icon' => 'uil:list-ul',
                'ordernumber' => 2,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 133,
                'fk_menu' => 131,
                'fk_system' => 1,
                'fk_modulemenu' => 132,
                'menulevel' => 2,
                'menu' => 'لیست چت ها',
                'menusec' => 'Login Report',
                'component' => 'modules/List',
                'secondcomponent' => NULL,
                'primarykey' => '',
                'icon' => 'uil:list-ul',
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 139,
                'fk_menu' => 138,
                'fk_system' => 7,
                'fk_modulemenu' => null,
                'menulevel' => 2,
                'menu' => 'لیست فعالیت ها',
                'menusec' => 'Event List',
                'component' => 'modules/List',
                'secondcomponent' => NULL,
                'primarykey' => '',
                'icon' => 'uil:list-ul',
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 140,
                'fk_menu' => 138,
                'fk_system' => 7,
                'fk_modulemenu' => null,
                'menulevel' => 2,
                'menu' => 'فعالیت های من',
                'menusec' => 'Event List',
                'component' => 'modules/List',
                'secondcomponent' => NULL,
                'primarykey' => '',
                'icon' => 'uil:list-ul',
                'ordernumber' => 1,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 141,
                'fk_menu' => 80,
                'fk_system' => 6,
                'fk_modulemenu' => 76,
                'menulevel' => 2,
                'menu' => 'لیست تسویه ها',
                'menusec' => 'Settle List',
                'component' => 'modules/List',
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => 'uil:money-stack',
                'ordernumber' => 4,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'pk_menu' => 143,
                'fk_menu' => 80,
                'fk_system' => 6,
                'fk_modulemenu' => 76,
                'menulevel' => 2,
                'menu' => 'تراکنش های آنلاین',
                'menusec' => 'Online Transaction',
                'component' => 'modules/List',
                'secondcomponent' => NULL,
                'primarykey' => NULL,
                'icon' => 'uil:money-stack',
                'ordernumber' => 5,
                'isenable' => 1,
                'created_at' => now(),
                'updated_at' => now()
            ],
        ]);

        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

    }
}
