<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;

use Illuminate\Database\Seeder;

class RMenusroleSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('r_menusroles')->insert([
            ['pk_menurole' => 1, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 1, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 2, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 2, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 3, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 3, 'editaccess' => 1, 'deleteaccess' => 1, 'printaccess' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 4, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 4, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 5, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 5, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 6, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 6, 'editaccess' => 1, 'deleteaccess' => 1, 'printaccess' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 7, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 7, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 8, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 8, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 9, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 9, 'editaccess' => 1, 'deleteaccess' => 1, 'printaccess' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 10, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 10, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 11, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 11, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 12, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 12, 'editaccess' => 1, 'deleteaccess' => 1, 'printaccess' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 13, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 13, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 14, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 14, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 15, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 15, 'editaccess' => 1, 'deleteaccess' => 1, 'printaccess' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 16, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 16, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 17, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 17, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 18, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 18, 'editaccess' => 1, 'deleteaccess' => 1, 'printaccess' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 19, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 19, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 20, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 20, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 21, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 21, 'editaccess' => 1, 'deleteaccess' => 1, 'printaccess' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 22, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 22, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 23, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 23, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 24, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 24, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 25, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 25, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 26, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 54, 'editaccess' => 1, 'deleteaccess' => 1, 'printaccess' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 27, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 27, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 28, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 28, 'editaccess' => 1, 'deleteaccess' => 1, 'printaccess' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 29, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 29, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 30, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 30, 'editaccess' => 1, 'deleteaccess' => 1, 'printaccess' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 31, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 31, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 32, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 32, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 33, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 33, 'editaccess' => 1, 'deleteaccess' => 1, 'printaccess' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 34, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 34, 'editaccess' => 1, 'deleteaccess' => 1, 'printaccess' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 37, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 37, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 38, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 38, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 39, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 39, 'editaccess' => 1, 'deleteaccess' => 1, 'printaccess' => 1, 'created_at' => now(), 'updated_at' => now()],
            //['pk_menurole' => 40,'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 40, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 41, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 41, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 42, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 42, 'editaccess' => 1, 'deleteaccess' => 1, 'printaccess' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 43, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 43, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 44, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 44, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 45, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 45, 'editaccess' => 1, 'deleteaccess' => 1, 'printaccess' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 46, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 46, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 47, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 47, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 48, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 48, 'editaccess' => 1, 'deleteaccess' => 1, 'printaccess' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 49, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 49, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 50, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 50, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 51, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 51, 'editaccess' => 1, 'deleteaccess' => 1, 'printaccess' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 52, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 52, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 53, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 53, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 54, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 26, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 55, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 55, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 56, 'fk_registrar' => 1, 'fk_role' => 3, 'fk_menu' => 57, 'editaccess' => 1, 'deleteaccess' => 1, 'printaccess' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 57, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 58, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 58, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 59, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 59, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 60, 'editaccess' => 1, 'deleteaccess' => 1, 'printaccess' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 60, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 61, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 61, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 62, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 62, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 63, 'editaccess' => 1, 'deleteaccess' => 1, 'printaccess' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 63, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 64, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 64, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 65, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 65, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 66, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 66, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 67, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 67, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 68, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 68, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 69, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 69, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 70, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 70, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 71, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 71, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 72, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 73, 'fk_registrar' => 1, 'fk_role' => 4, 'fk_menu' => 73, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 74, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 74, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 75, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 75, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 76, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 76, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 77, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 77, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 78, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 78, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 79, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 79, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 80, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 80, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 81, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 81, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 82, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 82, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 83, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 83, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 84, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 84, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 85, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 85, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 86, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 86, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 87, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 87, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 88, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 88, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 89, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 89, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 90, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 90, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 91, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 91, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 92, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 92, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 93, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 93, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 94, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 94, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 95, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 95, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 96, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 96, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 97, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 97, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 98, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 98, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 99, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 99, 'editaccess' => NULL, 'deleteaccess' => NULL, 'printaccess' => NULL, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 100, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 100, 'editaccess' => 1, 'deleteaccess' => 1, 'printaccess' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 101, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 101, 'editaccess' => 1, 'deleteaccess' => 1, 'printaccess' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 102, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 102, 'editaccess' => 1, 'deleteaccess' => 1, 'printaccess' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 103, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 103, 'editaccess' => 1, 'deleteaccess' => 1, 'printaccess' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 104, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 104, 'editaccess' => 1, 'deleteaccess' => 1, 'printaccess' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 105, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 105, 'editaccess' => 1, 'deleteaccess' => 1, 'printaccess' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 106, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 106, 'editaccess' => null, 'deleteaccess' => null, 'printaccess' => null, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 107, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 107, 'editaccess' => 1, 'deleteaccess' => 1, 'printaccess' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 108, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 108, 'editaccess' => null, 'deleteaccess' => null, 'printaccess' => null, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 109, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 109, 'editaccess' => null, 'deleteaccess' => null, 'printaccess' => null, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 110, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 110, 'editaccess' => 1, 'deleteaccess' => 1, 'printaccess' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 111, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 111, 'editaccess' => null, 'deleteaccess' => null, 'printaccess' => null, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 112, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 112, 'editaccess' => null, 'deleteaccess' => null, 'printaccess' => null, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 113, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 113, 'editaccess' => 1, 'deleteaccess' => 1, 'printaccess' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 114, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 114, 'editaccess' => null, 'deleteaccess' => null, 'printaccess' => null, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 115, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 115, 'editaccess' => null, 'deleteaccess' => null, 'printaccess' => null, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 116, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 116, 'editaccess' => 1, 'deleteaccess' => 1, 'printaccess' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 117, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 117, 'editaccess' => null, 'deleteaccess' => null, 'printaccess' => null, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 118, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 118, 'editaccess' => null, 'deleteaccess' => null, 'printaccess' => null, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 119, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 119, 'editaccess' => 1, 'deleteaccess' => 1, 'printaccess' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 120, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 120, 'editaccess' => null, 'deleteaccess' => null, 'printaccess' => null, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 121, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 121, 'editaccess' => null, 'deleteaccess' => null, 'printaccess' => null, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 122, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 122, 'editaccess' => 1, 'deleteaccess' => 1, 'printaccess' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 123, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 123, 'editaccess' => null, 'deleteaccess' => null, 'printaccess' => null, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 124, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 124, 'editaccess' => null, 'deleteaccess' => null, 'printaccess' => null, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 125, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 125, 'editaccess' => 1, 'deleteaccess' => 1, 'printaccess' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 126, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 126, 'editaccess' => null, 'deleteaccess' => null, 'printaccess' => null, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 127, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 127, 'editaccess' => null, 'deleteaccess' => null, 'printaccess' => null, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 129, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 129, 'editaccess' => null, 'deleteaccess' => null, 'printaccess' => null, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 130, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 130, 'editaccess' => null, 'deleteaccess' => null, 'printaccess' => null, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 131, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 131, 'editaccess' => null, 'deleteaccess' => null, 'printaccess' => null, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 132, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 132, 'editaccess' => null, 'deleteaccess' => null, 'printaccess' => null, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 133, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 133, 'editaccess' => null, 'deleteaccess' => null, 'printaccess' => null, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 134, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 134, 'editaccess' => null, 'deleteaccess' => null, 'printaccess' => null, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 135, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 135, 'editaccess' => null, 'deleteaccess' => null, 'printaccess' => null, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 136, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 136, 'editaccess' => null, 'deleteaccess' => null, 'printaccess' => null, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 137, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 137, 'editaccess' => null, 'deleteaccess' => null, 'printaccess' => null, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 138, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 138, 'editaccess' => null, 'deleteaccess' => null, 'printaccess' => null, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 139, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 139, 'editaccess' => null, 'deleteaccess' => null, 'printaccess' => null, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 140, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 140, 'editaccess' => null, 'deleteaccess' => null, 'printaccess' => null, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 141, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 141, 'editaccess' => null, 'deleteaccess' => null, 'printaccess' => null, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 142, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 142, 'editaccess' => null, 'deleteaccess' => null, 'printaccess' => null, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 143, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 143, 'editaccess' => null, 'deleteaccess' => null, 'printaccess' => null, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 144, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 144, 'editaccess' => null, 'deleteaccess' => null, 'printaccess' => null, 'created_at' => now(), 'updated_at' => now()],
            ['pk_menurole' => 145, 'fk_registrar' => 1, 'fk_role' => 2, 'fk_menu' => 145, 'editaccess' => null, 'deleteaccess' => null, 'printaccess' => null, 'created_at' => now(), 'updated_at' => now()]
        ]);
    }
}
